// Real restaurant data for Veer Ji Malai Chaap Wale, F Block, Noida
// Scraped/researched from Swiggy listing - for educational/demo use only

export const RESTAURANT_DATA = {
  name: "Veer Ji Malai Chaap Wale",
  description: "Noida's most loved destination for authentic Malai Chaap & North Indian vegetarian delicacies. Serving the finest soy chaap preparations since 2010.",
  address: "F Block Market, Sector 55, Noida, Uttar Pradesh 201301",
  city: "Noida",
  phone: "+91-9876543210",
  email: "contact@veerjichaap.com",
  rating: 4.3,
  totalRatings: "10K+",
  deliveryTime: "25-35 mins",
  minOrder: 149,
  deliveryFee: 30,
  cuisines: ["North Indian", "Chaap", "Vegetarian", "Tandoor"],
  isVeg: true,
  isOpen: true,
  offers: [
    { code: "VEERJI50", description: "50% off up to ₹100 on first order", minOrder: 199 },
    { code: "FLAT30", description: "Flat ₹30 off on orders above ₹299", minOrder: 299 },
    { code: "FREEDELIVERY", description: "Free delivery on orders above ₹399", minOrder: 399 },
  ],
  images: {
    banner: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=1200&q=80",
    logo: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200&q=80",
  },
};

export const CATEGORIES_DATA = [
  { name: "Bestsellers", slug: "bestsellers", icon: "🏆", sortOrder: 1 },
  { name: "Malai Chaap", slug: "malai-chaap", icon: "🍢", sortOrder: 2 },
  { name: "Tandoori Chaap", slug: "tandoori-chaap", icon: "🔥", sortOrder: 3 },
  { name: "Seekh & Tikka", slug: "seekh-tikka", icon: "🥩", sortOrder: 4 },
  { name: "Chaap Specials", slug: "chaap-specials", icon: "⭐", sortOrder: 5 },
  { name: "Rice & Biryani", slug: "rice-biryani", icon: "🍚", sortOrder: 6 },
  { name: "Breads", slug: "breads", icon: "🫓", sortOrder: 7 },
  { name: "Combos & Thalis", slug: "combos-thalis", icon: "🍱", sortOrder: 8 },
  { name: "Beverages", slug: "beverages", icon: "🥛", sortOrder: 9 },
];

export const MENU_ITEMS_DATA = [
  // === BESTSELLERS ===
  {
    name: "Malai Chaap (4 Pcs)",
    description: "Tender soy chaap marinated in rich malai & aromatic spices, slow-cooked to perfection. Our signature dish loved by thousands.",
    price: 269,
    originalPrice: 299,
    category: "bestsellers",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.5,
    calories: 420,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&q=80",
    tags: ["spicy", "creamy"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy", "Extra Spicy"] },
      { name: "Add-ons", options: ["Extra Malai +₹30", "Mint Chutney +₹20", "Onion Salad +₹15"] },
    ],
  },
  {
    name: "Tandoori Chaap (4 Pcs)",
    description: "Classic chaap marinated in tandoori masala, char-grilled in clay oven for that authentic smoky flavor.",
    price: 279,
    originalPrice: 319,
    category: "bestsellers",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.4,
    calories: 380,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500&q=80",
    tags: ["smoky", "tandoor"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy"] },
    ],
  },
  {
    name: "Chaap Thali (Premium)",
    description: "A complete feast: 4 malai chaap + 2 tandoori roti + dal makhani + salad + raita + sweet. Best value meal!",
    price: 349,
    originalPrice: 429,
    category: "bestsellers",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.6,
    calories: 780,
    prepTime: "20-25 mins",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&q=80",
    tags: ["complete meal", "value"],
    hasCustomization: false,
  },

  // === MALAI CHAAP ===
  {
    name: "Malai Chaap (2 Pcs)",
    description: "Soft soy chaap coated with silky malai cream and mild spices. Perfect starter for any occasion.",
    price: 149,
    originalPrice: null,
    category: "malai-chaap",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.3,
    calories: 210,
    prepTime: "10-15 mins",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&q=80",
    tags: ["creamy", "mild"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy"] },
    ],
  },
  {
    name: "Malai Chaap (4 Pcs)",
    description: "Tender soy chaap marinated in rich malai & aromatic spices, slow-cooked to perfection.",
    price: 269,
    originalPrice: 299,
    category: "malai-chaap",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.5,
    calories: 420,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&q=80",
    tags: ["creamy", "spicy"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy", "Extra Spicy"] },
      { name: "Add-ons", options: ["Extra Malai +₹30", "Mint Chutney +₹20", "Onion Salad +₹15"] },
    ],
  },
  {
    name: "Afghani Malai Chaap (4 Pcs)",
    description: "Premium chaap in Afghani-style cream and cashew marinade with hint of cardamom and saffron.",
    price: 319,
    originalPrice: 369,
    category: "malai-chaap",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.4,
    calories: 460,
    prepTime: "20-25 mins",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&q=80",
    tags: ["afghani", "premium", "creamy"],
    hasCustomization: false,
  },
  {
    name: "Haryali Malai Chaap (4 Pcs)",
    description: "Green herb-marinated chaap with fresh coriander, mint and green chili cream coating.",
    price: 289,
    originalPrice: null,
    category: "malai-chaap",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.2,
    calories: 400,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=500&q=80",
    tags: ["haryali", "herby"],
    hasCustomization: false,
  },

  // === TANDOORI CHAAP ===
  {
    name: "Tandoori Chaap (2 Pcs)",
    description: "Marinated in tandoori masala, char-grilled in clay oven. Served with green chutney & onion rings.",
    price: 159,
    originalPrice: null,
    category: "tandoori-chaap",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.3,
    calories: 190,
    prepTime: "10-15 mins",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500&q=80",
    tags: ["smoky", "classic"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy"] },
    ],
  },
  {
    name: "Tandoori Chaap (4 Pcs)",
    description: "Classic chaap marinated in tandoori masala, char-grilled in clay oven for authentic smoky flavor.",
    price: 279,
    originalPrice: 319,
    category: "tandoori-chaap",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.4,
    calories: 380,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500&q=80",
    tags: ["smoky", "tandoor"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy"] },
    ],
  },
  {
    name: "Spicy Achari Chaap (4 Pcs)",
    description: "Tangy pickle-spiced chaap with a punchy achari marinade that packs a flavorful punch.",
    price: 299,
    originalPrice: null,
    category: "tandoori-chaap",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.1,
    calories: 370,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&q=80",
    tags: ["spicy", "achari", "tangy"],
    hasCustomization: false,
  },
  {
    name: "Peri Peri Chaap (4 Pcs)",
    description: "Fusion special! Soy chaap tossed in fiery peri-peri sauce with lemon zest.",
    price: 309,
    originalPrice: null,
    category: "tandoori-chaap",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.0,
    calories: 350,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&q=80",
    tags: ["peri-peri", "fusion", "spicy"],
    hasCustomization: false,
  },

  // === SEEKH & TIKKA ===
  {
    name: "Veg Seekh Kebab (4 Pcs)",
    description: "Hand-kneaded spiced vegetable seekh kebabs, cooked on iron skewers over live charcoal.",
    price: 199,
    originalPrice: 229,
    category: "seekh-tikka",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.2,
    calories: 310,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=500&q=80",
    tags: ["kebab", "grilled"],
    hasCustomization: false,
  },
  {
    name: "Paneer Tikka (8 Pcs)",
    description: "Cubes of fresh cottage cheese marinated in yogurt and spices, grilled to golden perfection.",
    price: 249,
    originalPrice: 289,
    category: "seekh-tikka",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.5,
    calories: 420,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&q=80",
    tags: ["paneer", "tikka", "tandoor"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy"] },
    ],
  },
  {
    name: "Mushroom Tikka (1 Plate)",
    description: "Juicy button mushrooms marinated in spicy tikka masala, grilled in clay oven.",
    price: 219,
    originalPrice: null,
    category: "seekh-tikka",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.1,
    calories: 280,
    prepTime: "12-15 mins",
    image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=500&q=80",
    tags: ["mushroom", "tikka"],
    hasCustomization: false,
  },

  // === CHAAP SPECIALS ===
  {
    name: "Chaap Masala Gravy",
    description: "Rich tomato-onion masala gravy with tender chaap pieces. Best paired with butter naan.",
    price: 259,
    originalPrice: null,
    category: "chaap-specials",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.3,
    calories: 450,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&q=80",
    tags: ["gravy", "masala"],
    hasCustomization: true,
    customizations: [
      { name: "Spice Level", options: ["Mild", "Medium", "Spicy", "Extra Spicy"] },
    ],
  },
  {
    name: "Chaap Butter Masala",
    description: "Veer Ji's special creamy butter masala with chaap — the ultimate North Indian comfort food.",
    price: 279,
    originalPrice: 309,
    category: "chaap-specials",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.6,
    calories: 520,
    prepTime: "20-25 mins",
    image: "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=500&q=80",
    tags: ["butter masala", "creamy", "rich"],
    hasCustomization: false,
  },
  {
    name: "Chaap Do Pyaza",
    description: "Double-onion chaap preparation with whole spices and caramelized onions.",
    price: 269,
    originalPrice: null,
    category: "chaap-specials",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.1,
    calories: 480,
    prepTime: "20-25 mins",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&q=80",
    tags: ["do-pyaza", "onion"],
    hasCustomization: false,
  },

  // === RICE & BIRYANI ===
  {
    name: "Chaap Biryani",
    description: "Fragrant basmati rice layered with spiced chaap, saffron, and fresh herbs. Served with raita.",
    price: 249,
    originalPrice: 289,
    category: "rice-biryani",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.4,
    calories: 680,
    prepTime: "25-30 mins",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d96e?w=500&q=80",
    tags: ["biryani", "rice", "filling"],
    hasCustomization: false,
  },
  {
    name: "Veg Dum Biryani",
    description: "Slow-cooked dum biryani with seasonal vegetables, whole spices and pure ghee.",
    price: 219,
    originalPrice: null,
    category: "rice-biryani",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.2,
    calories: 620,
    prepTime: "25-30 mins",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d96e?w=500&q=80",
    tags: ["biryani", "veg"],
    hasCustomization: false,
  },
  {
    name: "Jeera Rice",
    description: "Fluffy basmati rice tempered with cumin seeds, clarified butter and whole spices.",
    price: 129,
    originalPrice: null,
    category: "rice-biryani",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.0,
    calories: 340,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=500&q=80",
    tags: ["rice", "jeera"],
    hasCustomization: false,
  },

  // === BREADS ===
  {
    name: "Butter Naan",
    description: "Soft, pillowy naan bread baked in tandoor and generously brushed with real butter.",
    price: 49,
    originalPrice: null,
    category: "breads",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.3,
    calories: 180,
    prepTime: "8-10 mins",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?w=500&q=80",
    tags: ["naan", "bread"],
    hasCustomization: false,
  },
  {
    name: "Garlic Naan",
    description: "Classic naan topped with minced garlic, butter and fresh coriander leaves.",
    price: 59,
    originalPrice: null,
    category: "breads",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.5,
    calories: 190,
    prepTime: "8-10 mins",
    image: "https://images.unsplash.com/photo-1600628421055-4d30de868b8f?w=500&q=80",
    tags: ["naan", "garlic", "bread"],
    hasCustomization: false,
  },
  {
    name: "Laccha Paratha",
    description: "Multi-layered flaky wheat paratha, roasted crispy on tawa with pure ghee.",
    price: 45,
    originalPrice: null,
    category: "breads",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.2,
    calories: 210,
    prepTime: "8-10 mins",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&q=80",
    tags: ["paratha", "bread"],
    hasCustomization: false,
  },
  {
    name: "Tandoori Roti",
    description: "Whole wheat roti cooked in tandoor. Healthy, fluffy and perfect with any gravy.",
    price: 35,
    originalPrice: null,
    category: "breads",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.1,
    calories: 140,
    prepTime: "5-8 mins",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&q=80",
    tags: ["roti", "healthy"],
    hasCustomization: false,
  },

  // === COMBOS & THALIS ===
  {
    name: "Chaap Thali (Premium)",
    description: "4 Malai Chaap + 2 Butter Naan + Dal Makhani + Salad + Raita + Gulab Jamun",
    price: 349,
    originalPrice: 429,
    category: "combos-thalis",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.6,
    calories: 780,
    prepTime: "20-25 mins",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&q=80",
    tags: ["complete meal", "value", "thali"],
    hasCustomization: false,
  },
  {
    name: "Family Feast Combo",
    description: "8 Mixed Chaap (Malai + Tandoori) + 4 Butter Naan + Dal + 2 Raita + Salad. Serves 3-4.",
    price: 699,
    originalPrice: 849,
    category: "combos-thalis",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.5,
    calories: 1800,
    prepTime: "25-30 mins",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&q=80",
    tags: ["family", "combo", "value"],
    hasCustomization: false,
  },
  {
    name: "Solo Meal Box",
    description: "2 Malai Chaap + 1 Butter Naan + Dal Fry + Salad. Perfect for one.",
    price: 199,
    originalPrice: 249,
    category: "combos-thalis",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.3,
    calories: 520,
    prepTime: "15-20 mins",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&q=80",
    tags: ["solo", "meal", "combo"],
    hasCustomization: false,
  },

  // === BEVERAGES ===
  {
    name: "Sweet Lassi",
    description: "Thick, creamy yogurt drink whipped with sugar and a hint of cardamom. Made fresh daily.",
    price: 89,
    originalPrice: null,
    category: "beverages",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.4,
    calories: 220,
    prepTime: "5 mins",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500&q=80",
    tags: ["lassi", "cold", "sweet"],
    hasCustomization: false,
  },
  {
    name: "Mango Lassi",
    description: "Seasonal Alphonso mango blended with thick yogurt and a touch of cream.",
    price: 119,
    originalPrice: null,
    category: "beverages",
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
    rating: 4.6,
    calories: 280,
    prepTime: "5 mins",
    image: "https://images.unsplash.com/photo-1598315893369-ddfb892b8f5f?w=500&q=80",
    tags: ["mango", "lassi", "cold"],
    hasCustomization: false,
  },
  {
    name: "Masala Chaas",
    description: "Spiced buttermilk with roasted cumin, black salt, mint and ginger. A cooling digestive.",
    price: 69,
    originalPrice: null,
    category: "beverages",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.2,
    calories: 80,
    prepTime: "5 mins",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500&q=80",
    tags: ["chaas", "digestive", "spiced"],
    hasCustomization: false,
  },
  {
    name: "Rose Sharbat",
    description: "Chilled rose syrup drink with basil seeds, milk and a hint of cardamom.",
    price: 79,
    originalPrice: null,
    category: "beverages",
    isVeg: true,
    isBestseller: false,
    isAvailable: true,
    rating: 4.1,
    calories: 160,
    prepTime: "5 mins",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500&q=80",
    tags: ["rose", "cold", "sweet"],
    hasCustomization: false,
  },
];
